# Generated by Django 6.0.7 on 2026-08-21 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VanBanPhapLuat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('so_hieu', models.CharField(max_length=100)),
                ('loai_vb', models.CharField(blank=True, max_length=100)),
                ('co_quan_ban_hanh', models.CharField(blank=True, max_length=200)),
                ('ngay_ban_hanh', models.DateField(blank=True, null=True)),
                ('ngay_hieu_luc', models.DateField(blank=True, null=True)),
                ('trich_yeu', models.TextField()),
                ('linh_vuc', models.CharField(blank=True, max_length=200)),
                ('trang_thai_hieu_luc', models.CharField(choices=[('con_hieu_luc', 'Còn hiệu lực'), ('het_hieu_luc', 'Hết hiệu lực'), ('sua_doi_bo_sung', 'Sửa đổi bổ sung'), ('chua_co_hieu_luc', 'Chưa có hiệu lực'), ('khong_ro', 'Không rõ')], default='khong_ro', max_length=30)),
                ('url_goc', models.URLField(blank=True, max_length=500)),
                ('url_file', models.URLField(blank=True, max_length=500)),
                ('nguon', models.CharField(choices=[('vbpl_api', 'API vbpl.vn'), ('moc_rss', 'RSS Bộ Xây dựng')], max_length=20)),
                ('uu_tien', models.BooleanField(default=False)),
                ('hien_thi', models.BooleanField(default=True)),
                ('da_canh_bao', models.BooleanField(default=False)),
                ('ngay_thu_thap', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-ngay_ban_hanh'],
                'indexes': [models.Index(fields=['linh_vuc'], name='legalvb_van_linh_vu_34c702_idx'), models.Index(fields=['-ngay_ban_hanh'], name='legalvb_van_ngay_ba_9e1194_idx')],
                'constraints': [models.UniqueConstraint(fields=('so_hieu', 'ngay_ban_hanh'), name='uniq_sohieu_ngaybanhanh')],
            },
        ),
    ]
