# Generated by Django 6.0.7 on 2026-08-28 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legalvb', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vanbanphapluat',
            name='nhom_nghiep_vu_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='vanbanphapluat',
            name='nhom_nghiep_vu_label',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddIndex(
            model_name='vanbanphapluat',
            index=models.Index(fields=['nhom_nghiep_vu_id'], name='legalvb_van_nhom_ng_09a281_idx'),
        ),
    ]
