# Generated by Django 6.0.7 on 2026-07-31 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Họ tên')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(max_length=20, verbose_name='Số điện thoại')),
                ('organization', models.CharField(blank=True, max_length=200, verbose_name='Cơ quan')),
                ('product_interest', models.CharField(default='all', max_length=50, verbose_name='Sản phẩm quan tâm')),
                ('message', models.TextField(blank=True, verbose_name='Nội dung')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Liên hệ',
                'verbose_name_plural': 'Liên hệ',
                'ordering': ['-created_at'],
            },
        ),
    ]
