# Generated by Django 6.0.7 on 2026-08-17 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='kind',
            field=models.CharField(choices=[('solution', 'Giải pháp AI'), ('product', 'Sản phẩm')], default='solution', max_length=20),
        ),
    ]
